# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addBookDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(270, 270)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../LibraryManageDesktopApp-master/LibraryManageDesktopApp-master/images/MainWindow_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.authNameEdit = QtWidgets.QLineEdit(Dialog)
        self.authNameEdit.setMaxLength(20)
        self.authNameEdit.setObjectName("authNameEdit")
        self.gridLayout.addWidget(self.authNameEdit, 2, 2, 1, 1)
        self.categoryLabel = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.categoryLabel.setFont(font)
        self.categoryLabel.setObjectName("categoryLabel")
        self.gridLayout.addWidget(self.categoryLabel, 3, 0, 1, 1)
        self.categoryComboBox = QtWidgets.QComboBox(Dialog)
        self.categoryComboBox.setObjectName("categoryComboBox")
        self.gridLayout.addWidget(self.categoryComboBox, 3, 2, 1, 1)
        self.bookNameEdit = QtWidgets.QLineEdit(Dialog)
        self.bookNameEdit.setText("")
        self.bookNameEdit.setMaxLength(10)
        self.bookNameEdit.setObjectName("bookNameEdit")
        self.gridLayout.addWidget(self.bookNameEdit, 0, 2, 1, 1)
        self.addNumLabel = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.addNumLabel.setFont(font)
        self.addNumLabel.setObjectName("addNumLabel")
        self.gridLayout.addWidget(self.addNumLabel, 6, 0, 1, 1)
        self.publishDateLabel = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.publishDateLabel.setFont(font)
        self.publishDateLabel.setObjectName("publishDateLabel")
        self.gridLayout.addWidget(self.publishDateLabel, 5, 0, 1, 1)
        self.bookIdLabel = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.bookIdLabel.setFont(font)
        self.bookIdLabel.setObjectName("bookIdLabel")
        self.gridLayout.addWidget(self.bookIdLabel, 1, 0, 1, 1)
        self.bookIdEdit = QtWidgets.QLineEdit(Dialog)
        self.bookIdEdit.setMaxLength(6)
        self.bookIdEdit.setObjectName("bookIdEdit")
        self.gridLayout.addWidget(self.bookIdEdit, 1, 2, 1, 1)
        self.authNameLabel = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.authNameLabel.setFont(font)
        self.authNameLabel.setObjectName("authNameLabel")
        self.gridLayout.addWidget(self.authNameLabel, 2, 0, 1, 1)
        self.publisherLabel = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.publisherLabel.setFont(font)
        self.publisherLabel.setObjectName("publisherLabel")
        self.gridLayout.addWidget(self.publisherLabel, 4, 0, 1, 1)
        self.addNumEdit = QtWidgets.QLineEdit(Dialog)
        self.addNumEdit.setMaxLength(12)
        self.addNumEdit.setObjectName("addNumEdit")
        self.gridLayout.addWidget(self.addNumEdit, 6, 2, 1, 1)
        self.publisherEdit = QtWidgets.QLineEdit(Dialog)
        self.publisherEdit.setMaxLength(20)
        self.publisherEdit.setObjectName("publisherEdit")
        self.gridLayout.addWidget(self.publisherEdit, 4, 2, 1, 1)
        self.bookNameLabel = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.bookNameLabel.setFont(font)
        self.bookNameLabel.setObjectName("bookNameLabel")
        self.gridLayout.addWidget(self.bookNameLabel, 0, 0, 1, 1)
        self.addBookButton = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.addBookButton.setFont(font)
        self.addBookButton.setObjectName("addBookButton")
        self.gridLayout.addWidget(self.addBookButton, 7, 2, 1, 1)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(Dialog)
        self.dateTimeEdit.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.dateTimeEdit.setWrapping(False)
        self.dateTimeEdit.setDate(QtCore.QDate(2000, 1, 8))
        self.dateTimeEdit.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.gridLayout.addWidget(self.dateTimeEdit, 5, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "添加书籍"))
        self.categoryLabel.setText(_translate("Dialog", "分   类："))
        self.addNumLabel.setText(_translate("Dialog", "数   量："))
        self.publishDateLabel.setText(_translate("Dialog", "出版日期："))
        self.bookIdLabel.setText(_translate("Dialog", "书   号："))
        self.authNameLabel.setText(_translate("Dialog", "作   者："))
        self.publisherLabel.setText(_translate("Dialog", "出版社："))
        self.bookNameLabel.setText(_translate("Dialog", "书   名："))
        self.addBookButton.setText(_translate("Dialog", "添加"))
        self.dateTimeEdit.setDisplayFormat(_translate("Dialog", "yyyy/M/d "))

