# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Book.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BookStorageViewer(object):
    def setupUi(self, BookStorageViewer):
        BookStorageViewer.setObjectName("BookStorageViewer")
        BookStorageViewer.resize(1057, 576)
        self.gridLayout = QtWidgets.QGridLayout(BookStorageViewer)
        self.gridLayout.setObjectName("gridLayout")
        self.tableView = QtWidgets.QTableView(BookStorageViewer)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.searchEdit = QtWidgets.QLineEdit(BookStorageViewer)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.searchEdit.setFont(font)
        self.searchEdit.setObjectName("searchEdit")
        self.horizontalLayout.addWidget(self.searchEdit)
        self.searchButton = QtWidgets.QPushButton(BookStorageViewer)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.searchButton.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./images/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchButton.setIcon(icon)
        self.searchButton.setObjectName("searchButton")
        self.horizontalLayout.addWidget(self.searchButton)
        self.condisionComboBox = QtWidgets.QComboBox(BookStorageViewer)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.condisionComboBox.setFont(font)
        self.condisionComboBox.setObjectName("condisionComboBox")
        self.horizontalLayout.addWidget(self.condisionComboBox)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.jumpToLabel = QtWidgets.QLabel(BookStorageViewer)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.jumpToLabel.setFont(font)
        self.jumpToLabel.setObjectName("jumpToLabel")
        self.horizontalLayout_2.addWidget(self.jumpToLabel)
        self.pageEdit = QtWidgets.QLineEdit(BookStorageViewer)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pageEdit.setFont(font)
        self.pageEdit.setObjectName("pageEdit")
        self.horizontalLayout_2.addWidget(self.pageEdit)
        self.pageLabel = QtWidgets.QLabel(BookStorageViewer)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pageLabel.setFont(font)
        self.pageLabel.setObjectName("pageLabel")
        self.horizontalLayout_2.addWidget(self.pageLabel)
        self.jumpToButton = QtWidgets.QPushButton(BookStorageViewer)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.jumpToButton.setFont(font)
        self.jumpToButton.setObjectName("jumpToButton")
        self.horizontalLayout_2.addWidget(self.jumpToButton)
        self.prevButton = QtWidgets.QPushButton(BookStorageViewer)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.prevButton.setFont(font)
        self.prevButton.setObjectName("prevButton")
        self.horizontalLayout_2.addWidget(self.prevButton)
        self.backButton = QtWidgets.QPushButton(BookStorageViewer)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.backButton.setFont(font)
        self.backButton.setObjectName("backButton")
        self.horizontalLayout_2.addWidget(self.backButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)

        self.retranslateUi(BookStorageViewer)
        QtCore.QMetaObject.connectSlotsByName(BookStorageViewer)

    def retranslateUi(self, BookStorageViewer):
        _translate = QtCore.QCoreApplication.translate
        BookStorageViewer.setWindowTitle(_translate("BookStorageViewer", "欢迎使用图书馆管理系统"))
        self.searchButton.setText(_translate("BookStorageViewer", "查询"))
        self.jumpToLabel.setText(_translate("BookStorageViewer", "跳转到第"))
        self.pageLabel.setText(_translate("BookStorageViewer", "TextLabel"))
        self.jumpToButton.setText(_translate("BookStorageViewer", "跳转"))
        self.prevButton.setText(_translate("BookStorageViewer", "前一页"))
        self.backButton.setText(_translate("BookStorageViewer", "后一页"))

