# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dropBookDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(333, 265)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../LibraryManageDesktopApp-master/LibraryManageDesktopApp-master/images/MainWindow_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.bookNameLabel = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.bookNameLabel.setFont(font)
        self.bookNameLabel.setObjectName("bookNameLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.bookNameLabel)
        self.bookIdLabel = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.bookIdLabel.setFont(font)
        self.bookIdLabel.setObjectName("bookIdLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.bookIdLabel)
        self.authNameLabel = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.authNameLabel.setFont(font)
        self.authNameLabel.setObjectName("authNameLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.authNameLabel)
        self.authNameEdit = QtWidgets.QLineEdit(Dialog)
        self.authNameEdit.setMaxLength(20)
        self.authNameEdit.setObjectName("authNameEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.authNameEdit)
        self.categoryLabel = QtWidgets.QLabel(Dialog)
        self.categoryLabel.setMaximumSize(QtCore.QSize(169, 16777215))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.categoryLabel.setFont(font)
        self.categoryLabel.setObjectName("categoryLabel")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.categoryLabel)
        self.categoryComboBox = QtWidgets.QComboBox(Dialog)
        self.categoryComboBox.setObjectName("categoryComboBox")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.categoryComboBox)
        self.publisherLabel = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.publisherLabel.setFont(font)
        self.publisherLabel.setObjectName("publisherLabel")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.publisherLabel)
        self.publisherEdit = QtWidgets.QLineEdit(Dialog)
        self.publisherEdit.setMaxLength(20)
        self.publisherEdit.setObjectName("publisherEdit")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.publisherEdit)
        self.publishDateLabel = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.publishDateLabel.setFont(font)
        self.publishDateLabel.setObjectName("publishDateLabel")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.publishDateLabel)
        self.publishTime = QtWidgets.QLineEdit(Dialog)
        self.publishTime.setObjectName("publishTime")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.publishTime)
        self.addNumLabel = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.addNumLabel.setFont(font)
        self.addNumLabel.setObjectName("addNumLabel")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.addNumLabel)
        self.addNumEdit = QtWidgets.QLineEdit(Dialog)
        self.addNumEdit.setMaxLength(12)
        self.addNumEdit.setObjectName("addNumEdit")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.addNumEdit)
        self.bookIdEdit = QtWidgets.QLineEdit(Dialog)
        self.bookIdEdit.setMaxLength(6)
        self.bookIdEdit.setObjectName("bookIdEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.bookIdEdit)
        self.bookNameEdit = QtWidgets.QLineEdit(Dialog)
        self.bookNameEdit.setText("")
        self.bookNameEdit.setMaxLength(10)
        self.bookNameEdit.setObjectName("bookNameEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.bookNameEdit)
        self.gridLayout.addLayout(self.formLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.dropBookButton = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.dropBookButton.setFont(font)
        self.dropBookButton.setObjectName("dropBookButton")
        self.horizontalLayout_4.addWidget(self.dropBookButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "删除书籍"))
        self.bookNameLabel.setText(_translate("Dialog", "书   名："))
        self.bookIdLabel.setText(_translate("Dialog", "书   号："))
        self.authNameLabel.setText(_translate("Dialog", "作   者："))
        self.categoryLabel.setText(_translate("Dialog", "分   类："))
        self.publisherLabel.setText(_translate("Dialog", "出版社："))
        self.publishDateLabel.setText(_translate("Dialog", "出版日期："))
        self.addNumLabel.setText(_translate("Dialog", "数   量："))
        self.dropBookButton.setText(_translate("Dialog", "删除"))

